# generic site meta
google_analytics_id: UA-44640221-1
fb_app_id: 522920774465173
url: https://emad.in
enforce_ssl: emad.in
domain: emad.in
author: Emad Alam
email: alam@emad.in
title: eMAD.in
social_profiles:
  - https://facebook.com/connect2emad
  - https://twitter.com/emadalam
  - https://www.linkedin.com/in/emadalam/
  - https://github.com/emadalam
  - https://www.instagram.com/im.emad/
blog_link: https://medium.com/@emadalam

# sitewise defaults
defaults:
  -
    scope:
        path: ""
    values:
        layout: site
meta:
  author: Emad Alam
  description: "Emad Alam is JavaScript Ninja and a seasoned web developer based out of Berlin, Germany specializing in front-end development. Creator of atvjs library (https://github.com/emadalam/atvjs) for AppleTV app development using JavaScript. In depth experience in cross-browser, cross-device, Rich Internet Application development using Advance JavaScript and related web technologies with a back-end knowledge of Java, JSP, ASP.NET with MVC, Adobe Experience Manager, PHP, nodejs, DBMS with MySQL and MS-SQL servers."


# standard jekyll configuration
highlighter: rouge
timezone: Europe/Berlin
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.txt
- CNAME
sass:
  style: compressed
github: [metadata]
