# generic site meta
google_analytics_id: UA-44640221-1
fb_app_id: 522920774465173
url: https://emad.in
enforce_ssl: emad.in
domain: emad.in
author: Emad Alam
email: alam@emad.in
title: eMAD.in
social_profiles:
  - https://facebook.com/connect2emad
  - https://twitter.com/emadalam
  - https://www.linkedin.com/in/emadalam/
  - https://github.com/emadalam
  - https://www.instagram.com/im.emad/
blog_link: https://blog.emad.in

# sitewise defaults
defaults:
  -
    scope:
        path: ""
    values:
        layout: site
meta:
  author: Emad Alam
  description: "Emad Alam is a Seasoned Developer, a Software Architect and a JavaScript fanatic based out of Berlin, Germany, specializing in product development. Creator of atvjs library (https://github.com/emadalam/atvjs) for AppleTV app development using JavaScript. With an in depth knowledge of the end-to-end systems, Emad Alam has helped companies build scalable systems and applications for their web, mobile and tv interface."


# standard jekyll configuration
highlighter: rouge
timezone: Europe/Berlin
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.txt
- CNAME
sass:
  style: compressed
github: [metadata]
